apiVersion: v1
kind: Service
metadata:
  name: {{ include "httpecho.fullname" . }}-serviceaccount
  labels:
    {{- include "httpecho.labels" . | nindent 4 }}
    component: app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "httpecho.selectorLabels" . | nindent 4 }}
    component: app
